# Generated by Django 5.2.6 on 2025-09-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holerite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: AAAA-MM', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holerites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('detalhes', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holerite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='api.holerite')),
            ],
        ),
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('detalhes', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holerite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencimentos', to='api.holerite')),
            ],
        ),
    ]
