# Generated by Django 5.2.6 on 2025-09-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_holerite_desconto_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='horas_mensais',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
