# Generated by Django 5.2.6 on 2025-09-22 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_registroponto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Registro'),
        ),
    ]
