# Generated by Django 5.2.6 on 2025-09-30 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_registroponto_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Registro'),
        ),
        migrations.CreateModel(
            name='Fechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: AAAA-MM', max_length=7, unique=True)),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('REVISAO', 'Em Revisão'), ('GERANDO', 'Gerando Holerites'), ('CONCLUIDO', 'Concluído')], default='INICIADO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('iniciado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_iniciados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoleriteGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_descontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enviado', models.BooleanField(default=False)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holerites_gerados', to='api.fechamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holerites_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
