# Generated by Django 5.2.6 on 2025-10-04 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_registroponto_timestamp_fechamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescontoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('detalhes', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holerite_gerado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos_gerados', to='api.holeritegerado')),
            ],
        ),
        migrations.CreateModel(
            name='VencimentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('detalhes', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holerite_gerado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencimentos_gerados', to='api.holeritegerado')),
            ],
        ),
    ]
