# Generated by Django 5.2.6 on 2025-10-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_descontogerado_vencimentogerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20),
        ),
    ]
