# Generated by Django 5.2.6 on 2025-10-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_registroponto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jornada_diaria',
            field=models.PositiveIntegerField(default=8, help_text='Jornada diária em horas'),
        ),
    ]
