# Generated by Django 5.2.6 on 2025-10-06 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_jornada_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Registro'),
        ),
    ]
