# Generated by Django 5.2.6 on 2025-11-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_logatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Indica se o usuário deve trocar a senha no próximo login'),
        ),
    ]
